### ISSUE TITLE
self.generator.load_state_dict(checkpoint["gen"])

### ISSUE THREAD

**Issue by shanjiayao** [alexzzhu/EventGAN#1]
when i use the pre-trained model to test
the error will occur like that :
```
Traceback (most recent call last):
  File "EventGAN/demo.py", line 35, in <module>
    EventGAN = EventGANBase(args)
  File "/home/echo/disks/DeepLearning_Projects/OpenSource/EventGAN-master/EventGAN/models/eventgan_base.py", line 25, in __init__
    self.generator.load_state_dict(checkpoint['gen'])
KeyError: 'gen'
```
So, could you tell me what's wrong? Thanks very much!

**Comment by alexzzhu** [comment]
What is the full command that you're running? Also, do you have either the pretrained model or a newly trained model stored in the logs folder?
